name: Futures Top5 (one-off)

on:
  workflow_dispatch:        # 只手动运行

jobs:
  run-top5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install requests

      - name: Run script (send to Telegram)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python top5_futures.py

      - name: Read message file
        id: readmsg
        shell: bash
        run: |
          MSG=$(cat message.txt)
          echo "msg<<EOF" >> $GITHUB_OUTPUT
          echo "$MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: "Gate 合约 涨幅榜前5"
          to: ${{ secrets.MAIL_USER }}
          from: GitHub Actions
          content_type: text/plain; charset=UTF-8
          body: ${{ steps.readmsg.outputs.msg }}
