name: Run Gate Strategy

on:
  schedule:
    - cron: "*/5 * * * *"   # 每5分钟运行一次
  workflow_dispatch:        # 也可以手动运行

jobs:
  run-strategy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run strategy
        run: python strategy.py
